services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\CrudHistoryBundle\Manager\:
        resource: '../../Manager/*'

    whatwedo\CrudHistoryBundle\Controller\:
        resource: '../../Controller/*'

    whatwedo\CrudHistoryBundle\Routing\:
        resource: '../../Routing/*'


    whatwedo\CrudHistoryBundle\Routing\CrudHistoryLoader:
        tags:
            - { name: routing.loader }

    whatwedo\CrudHistoryBundle\EventSubscriber\AuditTriggerSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'
              priority: 500